- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectVariableGetter.java
Make setting the NODE_NAME similar to what core does.
> Fix JENKINS-19222

- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPluginAction.java
The change just makes the static analysis happy.
There's no real concurrency issues.
Patch of the library: https://github.com/jenkinsci/envinject-lib/pull/4
Signed-off-by: Oleg Nenashev <o.v.nenashev@gmail.com>
> [JENKINS-27363] - Properly handle null sentitive variables

- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectBuildWrapperTest.java
When `WORKSPACE` env var already set, it replaces the custom build property injection.
As of you don't usually run jenkins inside of jenkins, this test can simply remove this var from env vars.
Also: simplify test-code without change of logic
Summon @oleg-nenashev for review
> fix for failed build on cloudbees (or other CI) 

- pom.xml
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectJobPropertyTest.java
One of tests is failing and indicate the real issue, which should be fixed IMO.
@reviewbybees @recena @lanwen
> Add new tests for EnvInjectJobProperty

- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectEnvVarsContributor.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectJobPropertyTest.java
> [WiP] There is a test failing after merge PR#56 and PR#56

- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectComputerListener.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectJobProperty.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectListener.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectNodeProperty.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPasswordWrapper.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectVarList.java
- src/main/java/org/jenkinsci/plugins/envinject/service/BuildCauseRetriever.java
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectActionSetter.java
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectEnvVars.java
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectScriptExecutor.java
- src/main/java/org/jenkinsci/plugins/envinject/service/PropertiesVariablesRetriever.java
> Findbugs cleanup

- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPluginAction.java
https://issues.jenkins-ci.org/browse/JENKINS-27382
@reviewbybees Could you review these changes?
> [JENKINS-27382] EnvInjectPluginAction::buildEnvVars() injects masks instead of passwords to the environment

- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectAction.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectBuildWrapper.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectBuilder.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPasswordWrapper.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPlugin.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPluginAction.java
While I was working on https://github.com/jenkinsci/envinject-plugin/pull/65 I saw some details that could be changed in order to improve a little the maintainability.
@reviewbybees
> Comments, Javadoc and deprecated methods

- README.md
Reverts jenkinsci/envinject-plugin#67
> Revert "Build status badge has been added in README.md"

- pom.xml
https://issues.jenkins-ci.org/browse/JENKINS-36466
@reviewbybees
> [JENKINS-36466] Update env-inject-lib to 1.24

- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectBuildWrapper.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectConstants.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectBuildWrapperTest.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectEnvVarsEmptyTest.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectEvaluatedGroovyScriptTest.java
Move initialization of WORKSPACE variable before run groovy script.
Some code clean-up.
Fix bug that eat exception message in case of script errors.
> Fix JENKINS-36545

- pom.xml
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectBuildWrapperTest.java
- src/test/java/org/jenkinsci/plugins/envinject/migration/EnvInjectMigrationBuildWrapperTest.java
This change updates Parent POM to the modern version. Failure on FindBugs errors is disabled since there are 17 bugs requiring some love.
@reviewbybees and @recena
> Update Plugin parent pom to 2.12

- pom.xml
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectAction.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectComputerListener.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectInfo.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectJobProperty.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectListener.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPasswordWrapper.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPluginAction.java
- src/main/java/org/jenkinsci/plugins/envinject/migration/EnvInjectMigrationListener.java
- src/main/java/org/jenkinsci/plugins/envinject/model/EnvInjectJobPropertyContributor.java
- src/main/java/org/jenkinsci/plugins/envinject/service/BuildCauseRetriever.java
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectActionSetter.java
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectEnvVars.java
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectGlobalPasswordRetriever.java
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectMasterEnvVarsSetter.java
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectPasswordsMasker.java
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectVariableGetter.java
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvironmentVariablesNodeLoader.java
- src/main/java/org/jenkinsci/plugins/envinject/service/PropertiesGetter.java
- src/main/java/org/jenkinsci/plugins/envinject/service/PropertiesLoader.java
- src/main/java/org/jenkinsci/plugins/envinject/service/PropertiesVariablesRetriever.java
- src/test/java/org/jenkinsci/plugins/envinject/GlobalPropertiesTest.java
Cleans up some issues reported by FindBugs after the core upgrade
> Findbugs cleanup. Continued

- pom.xml
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectPasswordMatrixProjectTest.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectPluginActionTest.java
@reviewbybees esp. @oleg-nenashev
> Use the latest test harness

- pom.xml
Integrated changes from EnvInject Lib 1.27:
* [JENKINS-46479](https://issues.jenkins-ci.org/browse/JENKINS-46479) - Prevent environment variables from being deleted on existing builds
* Parent POM and FindBugs cleanup: https://github.com/jenkinsci/envinject-lib/pull/12
Upstream PRs:
* https://github.com/jenkinsci/envinject-api-plugin/pull/3
* https://github.com/jenkinsci/envinject-lib/pull/12
> [JENKINS-46479] - Update to EnvInject API 1.3

- Jenkinsfile
- pom.xml
- src/test/java/org/jenkinsci/plugins/envinject/BuildCauseRetrieverTest.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectEvaluatedGroovyScriptTest.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectJobPropertyTest.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectPasswordMatrixProjectTest.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectPasswordTest.java
POM updates plus failures I noticed running against newer cores.
@reviewbybees esp. @oleg-nenashev
> PCT updates

- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectEnvVars.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectEvaluatedGroovyScriptTest.java
> [JENKINS-49154] - Resolve job run by BUILD_NUMBER string value instead of the Integer conversion

- pom.xml
> chore: Update maintainers metadata in pom.xml

- pom.xml
FYI @basil , preparing to the release with Guava cleanup
> Use Plugin BOM as a dependencies source + Update to Jenkins 2.303.x

- src/main/resources/org/jenkinsci/plugins/envinject/EnvInjectJobPropertyInfo/help-secureGroovyScript.html
I was reading the plugin docs in Jenkins and saw a minor typo so submitting a PR to fix. I didn't create a topic/feature/bugfix branch, Jira link, etc because this is documentation, not functionality.
> Fix typo in script security info
