- pom.xml
- src/main/java/org/jenkinsci/plugins/envinject/service/BuildCauseRetriever.java
- src/test/java/org/jenkinsci/plugins/envinject/BuildCauseRetrieverTest.java
- src/test/java/org/jenkinsci/plugins/envinject/matchers/WithEnvInjectActionMatchers.java
Fixes [JENKINS-28188](https://issues.jenkins-ci.org/browse/JENKINS-28188)
Example for reproduce (test added):
```java
FreeStyleBuild build = jenkins.createFreeStyleProject().scheduleBuild2(0, new Cause() {
@Override
public String getShortDescription() {
return "This build was started by a hobbit Bilbo. Bilbo Baggins";
}
}).get();
```
Exception:
```
[EnvInject] - Loading node environment variables.
FATAL: String index out of range: -1
http://stacktrace.jenkins-ci.org/search?query=java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.substring(String.java:1875) <http://stacktrace.jenkins-ci.org/search/?query=java.lang.String.substring&entity=method>
at org.jenkinsci.plugins.envinject.service.BuildCauseRetriever.buildCauseEnvironmentVariables(BuildCauseR …
```
> [FIXED JENKINS-28188] - Fix for plugin compatibility when used anonymous class cause

- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPasswordWrapper.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectPasswordTest.java
https://issues.jenkins-ci.org/browse/JENKINS-28409
@reviewbybees
> [FIXED JENKINS-28409] - Properly close parent streams in EnvInjectPasswordsOutputStream

- src/main/resources/index.jelly
Signed-off-by: Anders Hammar <anders@hammar.net>
> [FIXED JENKINS-29667] Text description in plugin manager shouldn't be in bold

- pom.xml
It's a follow-up to https://github.com/jenkinsci/envinject-lib/pull/4.
The plugin has been already patched in https://github.com/jenkinsci/envinject-plugin/commit/b78c45cc336b2875ca7e4da4c25c95c2235a4e1c, but it's better to use a new library to push it to other potential use cases. 
@reviewbybees @aheritier
> [JENKINS-27665] - Bump envinject-lib version dependency to 1.22

- pom.xml
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectJobProperty.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectEnvVarsEmpty.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectEvaluatedGroovyScript.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectPasswordMatrixProjectTest.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectPasswordTest.java
- src/test/java/org/jenkinsci/plugins/envinject/GlobalPropertiesTest.java
Update tests to avoid the deprecated HudsonTestCase:
@gboissinot, as maintainer of this plugin, I hope you consider useful these changes.
> Updated tests to use JenkinsRule

- pom.xml
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectAction.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPlugin.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPluginAction.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPluginConfiguration.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectVarList.java
- src/main/resources/org/jenkinsci/plugins/envinject/EnvInjectPluginConfiguration/config.jelly
- src/main/resources/org/jenkinsci/plugins/envinject/EnvInjectPluginConfiguration/config.properties
- src/main/resources/org/jenkinsci/plugins/envinject/EnvInjectPluginConfiguration/help-enablePermissions.html
- src/main/resources/org/jenkinsci/plugins/envinject/EnvInjectPluginConfiguration/help-hideInjectedVars.html
- src/main/resources/org/jenkinsci/plugins/envinject/Messages.properties
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectPluginActionTest.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectPluginConfigurationTest.java
https://issues.jenkins-ci.org/browse/JENKINS-29867
In several cases Jenkins users may expose passwords as a plain text in "Injected variables" action (e.g. password reassigning for a non-sensitive variable). It may make sense to add an option, which completely prohibits the exposure of environment variables.
Depends on https://github.com/jenkinsci/envinject-lib/pull/6
@reviewbybees
> [JENKINS-29867] - Permissions engine + global option for disabling the Injected vars

- src/main/resources/org/jenkinsci/plugins/envinject/EnvInjectPluginConfiguration/config.jelly
The change moves both security options to the Advanced section
@reviewbybees
> Refactoring (UX): Hide  options from the global EnvInject configuration

- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectEnvVars.java
Avoids the script content appearing in the build output entirely. This is the simplest possible change to fix this issue, but it also seems the most suitable.
This probably isn't the most high value issue against the plugin, but it would clear up my build logs so it would be nice. Thoughts?
> Fixes JENKINS-23274: remove log of script content

- src/main/java/org/jenkinsci/plugins/envinject/service/BuildCauseRetriever.java
- src/test/java/org/jenkinsci/plugins/envinject/sevice/BuildCauseRetrieverTest.java
Fixes the issue mentioned in https://groups.google.com/forum/#!topic/jenkinsci-dev/keV6a_YtzD0
> [FIXED JENKINS-32693] - Fix BuildCauseRetriever when AbstractBuild has Null CauseAction

- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPasswordWrapper.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectPasswordTest.java
[JENKINS-30028](https://issues.jenkins-ci.org/browse/JENKINS-30028)
When the Timestamper build wrapper runs first, the messages logged produced by EnvInjectPasswordWrapper.decorateLogger do not receive timestamps. Fix this by logging these messages from setUp instead.
I was able to reproduce this by using the [ordinal value](https://github.com/jenkinsci/jenkins/blob/2893fd3/core/src/main/java/hudson/Extension.java#L82) to force the Timestamper plugin to load first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/envinject-plugin/87)
> [FIXED JENKINS-30028] Remove logging from password wrapper decorateLogger

- pom.xml
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectComputerListener.java
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectActionSetter.java
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectMasterEnvVarsSetter.java
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvironmentVariablesNodeLoader.java
- src/main/java/org/jenkinsci/plugins/envinject/service/PropertiesVariablesRetriever.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectPluginActionTest.java
It supersedes #82. The reason for the upgrade is a need to pick security fixes available in newer Jenkins core versions. 1.609.3 is the target release, because newer version do not support Java 6.
After this release I hope to jump to Java 7 shortly since it could help with plugin code quality fixes.
> Update core dependency to 1.609.3

- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectEnvVars.java
- src/main/java/org/jenkinsci/plugins/envinject/service/PropertiesVariablesRetriever.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectBuildWrapperTest.java
- src/test/java/org/jenkinsci/plugins/envinject/sevice/PropertiesGetterTest.java
on a matrix job we had something like this line in "Properties Content":
`PATH=$WORKSPACE/git_checkout/bin:${PATH}`
it expanded recursively (`WORKSPACE` being quite long already for matrix runners) and `PATH` grew very large and I think it caused build failures later, where calling bash failed with:
`Argument list too long`
duplicate issues: JENKINS-30446, JENKINS-30445, JENKINS-30444
similar PR: #73 
Regarding changes in `PropertiesVariablesRetriever`:
this logic should probably be re-used more often across the whole code base instead of plain `putAll`, which just overwrites values.
Currently there are still many inconsistencies regarding referencing previously defined variables (see comment in Test `injectTextExtendSysEnvVar` for an example) but fixing all those issues is outside of the …
> JENKINS-30467 support common cases of recursive variables

- src/main/resources/org/jenkinsci/plugins/envinject/EnvInjectNodeProperty/config.jelly
- src/main/resources/org/jenkinsci/plugins/envinject/EnvInjectNodeProperty/help-propertiesFilePath.html
Just add a warning regarding [JENKINS-23666](https://issues.jenkins-ci.org/browse/JENKINS-23666), which got several issues in Jenkins. Also added a node regarding the startup-only behavior.
Occasionally got into [JENKINS-38487](https://issues.jenkins-ci.org/browse/JENKINS-38487) during testing. It's a core bug IMHO, still exists in the last version.
@reviewbybees @rsandell  @recena
> [JENKINS-23666] - Document the current behavior of NodeProperties

- pom.xml
- src/main/resources/index.jelly
- src/main/resources/org/jenkinsci/plugins/envinject/EnvInjectBuilder/config.jelly
- src/main/resources/org/jenkinsci/plugins/envinject/EnvInjectNodeProperty/config.jelly
- src/main/resources/org/jenkinsci/plugins/envinject/EnvInjectNodeProperty/global.jelly
- src/main/resources/org/jenkinsci/plugins/envinject/EnvInjectPasswordWrapper/config.jelly
- src/main/resources/org/jenkinsci/plugins/envinject/EnvInjectVarList/index.jelly
Also updates maven-hpi-version to the version declared in POM
* https://issues.jenkins-ci.org/browse/JENKINS-31573
* https://issues.jenkins-ci.org/browse/JENKINS-38607
@reviewbybees @rsandell @jenkinsci/code-reviewers
> [FIXED JENKINS-38607] - Add explicit compatibility notice for the JENKINS-31573 change

- src/main/resources/org/jenkinsci/plugins/envinject/EnvInjectJobPropertyInfo/help-secureGroovyScript.html
In the example in the help text, the key in the returned map should be a string from what I have tested. Otherwise groovy throws an exception like the following:
groovy.lang.MissingPropertyException: No such property: COMPUTE_VAR for class: xxx
> fix groovy script example in help text

- pom.xml
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectAction.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectBuildVariableContributor.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectBuildWrapper.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectBuilder$1.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectBuilder.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectJobProperty.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectListener.java
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPluginAction.java
- src/main/java/org/jenkinsci/plugins/envinject/model/EnvInjectJobPropertyContributor.java
- src/main/java/org/jenkinsci/plugins/envinject/service/BuildCauseRetriever.java
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectActionSetter.java
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectPasswordsMasker.java
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectVariableGetter.java
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvironmentVariablesNodeLoader.java
- src/main/java/org/jenkinsci/plugins/envinject/util/RunHelper.java
- src/test/java/org/jenkinsci/plugins/envinject/BuildCauseRetrieverTest.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectBuildWrapperTest.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectEvaluatedGroovyScriptTest.java
- src/test/java/org/jenkinsci/plugins/envinject/sevice/EnvInjectVariableGetterTest.java
The change streamlines the handling logic of non-AbstractProject job types. Some use-cases in Pipeline may start working.
* Update Core dependency to 1.625 in order to pick the new `Files` API
* [JENKINS-43845](https://issues.jenkins-ci.org/browse/JENKINS-43845) - Use EnvInject API Plugin
* [JENKINS-43535](https://issues.jenkins-ci.org/browse/JENKINS-43535) - Make API compatible with non-AbstractProject types
* [JENKINS-43536](https://issues.jenkins-ci.org/browse/JENKINS-43536) - Cleanup AbstractProject/AbstractBuild usages in the plugin
Upstream PRs:
* https://github.com/jenkinsci/envinject-lib/pull/8
* https://github.com/jenkinsci/envinject-api-plugin/pull/1
@reviewbybees
> [JENKINS-43536] - Avoid usage of AbstractProject/AbstractBuild where possible

- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectVarList.java
If environment variables or their values contain special characters, there is no valid xml respectively json output.
> [JENKINS-32428] Escape xml and json outputs in REST API

- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPluginAction.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectVarListTest.java
In EnvInject 3.1 I was doing refactoring for better Pipeline Support, and I have somehow removed cache calculation in the Build lazy loading chain. It caused regression (missing data) in `EnvInjectPluginAction#getEnvInjectVarList()`, which was always reading the cache value instead of invoking the Getter method. And there was no roundtrip tests...
https://issues.jenkins-ci.org/browse/JENKINS-44263
@reviewbybees
> [FIXED JENKINS-44263] - Get rid of explict cached value access.

- pom.xml
This issue definitely belongs to my hall of shame. I have not changed the packaging type in EnvInject API when I was releasing 1.0
* [JENKINS-45056](https://issues.jenkins-ci.org/browse/JENKINS-45056) - Fix issue with the incorrect plugin packaging in 1.0 due to the release flow issue.
* [JENKINS-45055](https://issues.jenkins-ci.org/browse/JENKINS-45055) - Update EnvInject Lib from 1.25 to 1.26 in order to pick FindBugs fixes ([changelog](https://github.com/jenkinsci/envinject-lib/blob/master/CHANGELOG.md#126)).
Diffs
* EnvInject Lib Diff: jenkinsci/envinject-lib@envinject-lib-1.25...envinject-lib-1.26
* EnvInject API Diff: https://github.com/jenkinsci/envinject-api-plugin/compare/envinject-api-1.0...envinject-api-1.2
@reviewbybees
> [JENKINS-45056] - Update to EnvInject API bundled as a plugin + pick new EnvInject Lib

- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectVarList.java
I added the replaces in wrong order at #120.
`"C:\Program Files\Java\jre1.8.0_131\bin"` got escaped with `\\"C:\\Program Files\\Java\\jre1.8.0_131\\bin\\"` which isn't valid json. The correct escaped string is `\"C:\\Program Files\\Java\\jre1.8.0_131\\bin\"`
@oleg-nenashev ping
> [JENKINS-32428] Escape xml and json outputs in REST API - fix 2 (#120)

- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectListener.java
- src/test/java/org/jenkinsci/plugins/envinject/BuildCauseRetrieverTest.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectActionTest.java
[JENKINS-26583](https://issues.jenkins-ci.org/browse/JENKINS-26583)
> [WIP][JENKINS-26583] Env-inject suppress variables contributed by extension points

- pom.xml
Instead of blacklisting of the plugin now, I decided to add a compatibility notice for now while I investigate the issue and create test cases for the reported regressions. [Wiki](https://wiki.jenkins.io/display/JENKINS/EnvInject+Plugin) is explicit enough of the notice reasons.
@nfalco79 @dwnusbaum
> Add compatibility notice for JENKINS-47364 and JENKINS-47370

- src/main/resources/org/jenkinsci/plugins/envinject/EnvInjectJobPropertyInfo/help-secureGroovyScript.html
Fixed a nasty type in the help section (for all of those who copy the variable names).
> Fix type currentBuid to currentBuild

- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectActionSetter.java
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvironmentVariablesNodeLoader.java
org.jenkinsci.remoting.util.AnonymousClassWarnings warn:
WARNING: Attempt to (de-)serialize anonymous class org.jenkinsci.plugins.envinject.service.EnvironmentVariablesNodeLoader$1
WARNING: Attempt to (de-)serialize anonymous class org.jenkinsci.plugins.envinject.service.EnvInjectActionSetter$1
see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
> Convert anonymous MasterToSlaveFileCallable to member

- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPasswordWrapper.java
Add @DataBoundSetter annotation for envInjectPasswordWrapper setters to be able to configure envInjectPasswordWrapper by job DSL.
> Add DataBoundSetter for EnvInjectPasswordWrapper setters to make them compatible with JobDSL

- pom.xml
I would like to apply some patches and to ensure that the new version builds with Java 11
> Update Jenkins core dependency to 2.138.4 + plugin POM facelift

- pom.xml
- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPluginConfiguration.java
- src/test/java/org/jenkinsci/plugins/envinject/EnvInjectPluginConfigurationTest.java
- src/test/resources/org/jenkinsci/plugins/envinject/configuration-as-code.yml
[JENKINS-56449](https://issues.jenkins-ci.org/browse/JENKINS-56449)
Based on https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/PLUGINS.md, adds support for defining EnvInject plugin global configuration within the configuration-as-code plugin.
> [JENKINS-56449] - Add support for global config via configuration-as-code plugin

- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectComputerListener.java
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectMasterEnvVarsRetriever.java
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvironmentVariablesNodeLoader.java
The warning from org.jenkinsci.remoting.util.AnonymousClassWarnings was:
> WARNING: Attempt to (de-)serialize anonymous class org.jenkinsci.plugins.envinject.EnvInjectComputerListener$1
> see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
It seems this anonymous class was missed in #134 @jsoref.
Hopefully this is the last fix in this regard. At least for `Callable` it should be fine now (`grep -rP 'new.*Callable.*{' src/` does not find anything else).
> Fix anonymous class serialization warning in EnvInjectComputerListener 

- src/main/java/org/jenkinsci/plugins/envinject/service/PropertiesLoader.java
- src/test/java/org/jenkinsci/plugins/envinject/sevice/PropertiesLoaderTest.java
Windows paths can now be used without the need to change all properties files to have the escaped \\ character
There is some funkyness that I had to regex for inside of the code in order to have /n work as intended. I just ignored all /n and //n that happens to ensure that the previous behavior is not touched. Maybe we should change that eventually but I wanted to focus my efforts on arbitrary / characters
> [JENKINS-39403] - Automatically escape single backslashes in the properties loader

- src/main/java/org/jenkinsci/plugins/envinject/service/PropertiesLoader.java
- src/test/java/org/jenkinsci/plugins/envinject/sevice/PropertiesLoaderTest.java
Follow up to #133 to add a test to prevent this functionality from breaking unknowingly.
> [JENKINS-39403] - Add test and simple cleanup

- src/main/java/org/jenkinsci/plugins/envinject/service/PropertiesLoader.java
- src/test/java/org/jenkinsci/plugins/envinject/sevice/PropertiesLoaderTest.java
For windows paths #133 misses out the case of network shares where network shares begin with a double backslash. This PR adds that capability and a functional test for it.
> Escape paths for network shares

- pom.xml
Picks up https://github.com/jenkinsci/envinject-lib/pull/19 via https://github.com/jenkinsci/envinject-api-plugin/pull/17 and runs against a core JEP-228 to verify `EnvInjectVarListTest.envVarsShouldBeCachedProperlyAfterReload`.
> [JENKINS-64398] - Update EnvInject API to 1.8

- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectAction.java
- src/main/resources/util/hetero-list-readonly.jelly
Preparation for core sunsetting dated icons: `https://github.com/jenkinsci/jenkins/pull/5778`
@oleg-nenashev Would be nice if you can also trigger a release after merging this PR. The core PR is blocked until then.
Thanks in advance!
(May dismiss if this plugin is actually no longer maintained, I was solely going of SCM activity)
> chore: Prepare for sunset icon removal from core

- src/main/java/org/jenkinsci/plugins/envinject/EnvInjectEnvVarsContributor.java
When similarly-named environment variables with different case are defined as job properties, they will be treated as one variable and overwrite each other. `EnvVars` appears to treat variables in a case-insensitive manner by design, so if altering the existing behavior is not an option, a warning regarding this behavior should at least be logged to prevent confusion.
> JENKINS-60559: Log warning when not all environment variables can be injected

- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectMasterEnvVarsSetter.java
See [JENKINS-66896](https://issues.jenkins.io/browse/JENKINS-66896) and [JENKINS-68930](https://issues.jenkins.io/browse/JENKINS-68930)
Use WA to work with modifiers field filtered since JDK12.
--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED are required.
> [JENKINS-68930] Fix Java17 Error on agent start

- pom.xml
- src/test/java/org/jenkinsci/plugins/envinject/util/TestUtils.java
Remove locked dependencies from https://github.com/jenkinsci/envinject-plugin/pull/268 after adapting tests to make them pass. This updates some plugin dependencies.
See [JENKINS-71658](https://issues.jenkins.io/browse/JENKINS-71658).
Ran autotests only, as this is a test-only issue.
```[tasklist]
```
> [JENKINS-71658] Update plugin dependencies

- Jenkinsfile
- pom.xml
- src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectVariableGetter.java
Java 21 released Sep 19, 2023. We'd like to announce full support for Java 21 in early October and would like the most used plugins to be compiling and testing with Java 21.
The acceptance test harness and plugin bill of materials tests are already passing with Java 21. This is a further step to improve plugin readiness for use with Java 21 and for development with Java 21.
Java 11 will be unsupported by Eclipse Temurin and some other Java providers in October 2024. We'll need to move past Java 11 by that time. It does not change the supported Java version or the byte code that is being generated. This intentionally does not include Java 11 in the test configuration because Java 11 byte code is being generated by the Java 17 and Java 21 compilation and because Java 11 is being tested at …
> Test with Java 21
